baseURL: https://claytoneasley.org
languageCode: en-us
title: Clayton Easley
theme: PaperModX
author:
  name: Clayton Easley


googleAnalytics: G-M50KSRMNSP

###Search###

outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary

# fuseOpts:
#   isCaseSensitive: false
#   shouldSort: true
#   location: 0
#   distance: 1000
#   threshold: 0.4
#   minMatchCharLength: 0

###Search###

params:
  env: production
  Description: "Hi my name is Clayton. I am a hobbyist interested in a plethora of things including but not limited to, programming, photography, electronics, art, welding, robots, and machine learning."
  defaultTheme: dark
  TocSide: left
  external: true
  
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

  keywords: [Blog, Portfolio, Engineering, Computers, Codeing]

  homeInfoParams:
    Title: "Welcome to my site"
    Content: 
      "Welcome to my blog! This is where I document all my projects and Ideas to share with you. 
      If you like the content consider sharing with a friend ðŸ˜ƒ.\n\n
      If you want to contact to me you can send me an email at askme@claytoneasley.org \n\nor click the mail button below"
      
  socialIcons:
    - name: github
      url: https://github.com/clayton14
    - name: instagram
      url: https://www.instagram.com/claytoneasley77/
    - name: linkedin
      url: https://www.linkedin.com/in/clayton-easley/
    - name: email
      url: mailto:askme@claytoneasley.org

  cover:
    linkFullImages: false
  
  editPost:
    URL: https://github.com/clayton14/MySite2.0
    Text: "Suggest Changes"
    appendFilePath: true 
   


menu:
  main:
  - identifier: Search
    name: Search 
    weight: 5
    url: /search/
  - identifier: categories
    name: All Categories
    url: /categories/
    weight: 20
  - identifier: projects
    name: Projects
    url: /posts/myprojects/
    weight: 15
  # - identifier: engnieering
  #   name: Engnieering
  #   url: /posts/engnieering
  #   weight: 15

